version: "3"

dotenv: ['.env']

env:
  CGO_CPPFLAGS: -I /opt/homebrew/include
  CGO_LDFLAGS: -L /opt/homebrew/lib

tasks:
  test:
    cmds:
      - go test github.com/paveldroo/go-ogg-packer/cgo/lib/ogg_packer/writer -run "TestOggPacker"
