version: "3"

dotenv: ['.env']

env:
  BASE_IMAGE: paveldroo/go-ogg-packer:base

tasks:
  install-mac-deps:
    desc: Install external dependencies for macOS
    cmds:
      - brew install opus

  install-linux-deps:
    desc: Install external dependencies for Linux
    cmds:
      - apt-get update && apt-get install libopus-dev

  pretty:
    desc: Prettify code
    cmds:
      - golangci-lint fmt

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test -v -shuffle=on -cover -race ./...

  docker-build:
    desc: Build docker image
    cmds:
      - docker build --platform=linux/amd64 -t {{.BASE_IMAGE}} -f Dockerfile .

  docker-push:
    desc: Push image to Docker Hub
    cmds:
      - docker push docker.io/{{.BASE_IMAGE}}

  docker-test:
    desc: Run tests in docker
    cmds:
      - task docker-build
      - docker run {{.BASE_IMAGE}} task test

  docker-generate-ogg:
    desc: Generate ogg reference file for tests on Linux
    cmds:
      - task docker-build
      - docker run -v "{{.PWD}}/examples/:/app/examples/" {{.BASE_IMAGE}} go run examples/main.go
